package se.kth.id2203.simulation.beb;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import se.kth.id2203.beb.event.BebDeliver;
import se.kth.id2203.beb.event.BebRequest;
import se.kth.id2203.beb.port.BebPort;
import se.kth.id2203.networking.NetAddress;
import se.sics.kompics.*;
import se.sics.kompics.timer.ScheduleTimeout;
import se.sics.kompics.timer.Timeout;
import se.sics.kompics.timer.Timer;


/**
 * Created by YannL on 13/02/2017.
 */
public class Sender extends ComponentDefinition {
    final static Logger LOG = LoggerFactory.getLogger(Sender.class);
    //******* Ports ******
    protected final Positive<BebPort> beb = requires(BebPort.class);
    protected final Positive<Timer> timer = requires(Timer.class);
    //******* Fields ******
    private final NetAddress self;

    //******* Handlers ******
    protected final Handler<Start> startHandler = new Handler<Start>() {
        @Override
        public void handle(Start start) {
            LOG.info("[Sender] Start sender " + self);
            ScheduleTimeout spt = new ScheduleTimeout(2000);
            spt.setTimeoutEvent(new SendTimeout(spt));
            trigger(spt, timer);
        }
    };

    protected final Handler<SendTimeout> timeoutHandler = new Handler<SendTimeout>() {
        @Override
        public void handle(SendTimeout timeout) {
            LOG.debug("[Sender] Timeout received by " + self);
            BebRequest bebRequest = new BebRequest(null);
            trigger(bebRequest, beb);
        }
    };


    protected final Handler<BebDeliver> bebDeliverHandler = new Handler<BebDeliver>() {
        @Override
        public void handle(BebDeliver bebDeliver) {
            LOG.info("[Sender] BebDeliver from " + bebDeliver.source + " received by node " + self.toString());
        }
    };


    public Sender(Init init) {
        this.self = init.self;

        subscribe(startHandler, control);
        subscribe(bebDeliverHandler, beb);
        subscribe(timeoutHandler, timer);
    }

    public static class Init extends se.sics.kompics.Init<Sender> {
        public final NetAddress self;

        public Init(NetAddress self) {
            this.self = self;
        }
    }

    /**
     * Timeout event generated by the Timer after starting the sender
     */
    private class SendTimeout extends Timeout {

        protected SendTimeout(ScheduleTimeout request) {
            super(request);
        }
    }
}
